### ISSUE TITLE
Escaped slashes

### ISSUE THREAD

**Issue by mariorovaris** [vemcogroup/laravel-translation#12]
Hi!

I'm having problems with slashes in my terms, like when I have html tags.

I would suggest adding `JSON_UNESCAPED_SLASHES` in this [line](https://github.com/vemcogroup/laravel-translation/blob/9d72755925c44bff7cb64868f786dafa23245422/src/Translation.php#L79).

**Comment by NaincyKumariKnoldus** [comment]
Hey @mariorovaris I really liked to do this and I have raised a PR for this now.
Please review my PR.
Thanks!

**Comment by mariorovaris** [comment]
@NaincyKumariKnoldus awesome!
That change will be pretty good
Thanks!

**Comment by NaincyKumariKnoldus** [comment]
Thankyou so much @mariorovaris

**Comment by eldor** [comment]
Hi both, thank you for the issue and PR, i'll look into it today.
Just for information, we do suggest to use words or phrases as terms for translations and not including html.

But if there aren't any problems with the PR, ill approve and make a minor version bump.

Have a nice day.

**Comment by eldor** [comment]
PR #13 merged and tagged 3.0.5
