### ISSUE TITLE
Installation on Laravel 9 conflict (symfony/finder v6.0.3)

### ISSUE THREAD

**Issue by inikoo** [vemcogroup/laravel-translation#14]
Hi, Laravel 9 packs  symfony/finder v6.0.3 so can not be installed, a small change in composer.json line 23 needed 

`- vemcogroup/laravel-translation[3.0.3, ..., 3.0.6] require symfony/finder ^4.3|^5.0 -> found symfony/finder[v4.3.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v6.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.`

**Comment by makije** [comment]
Hi @inikoo 

Please have a look at the latest version that I just release, thank you for filing the issue-
