### ISSUE TITLE
Comma doesn't work

### ISSUE THREAD

**Issue by RonJeremyR6** [vemcogroup/laravel-translation#17]
When I have a translation like this:
`__('Subsequently click on \'scan a barcode\', after which the camera will activate, and point the camera at the QR code.')`

The translation will be created is:
`"Subsequently click on \\'scan a barcode\\": "Subsequently click on \\'scan a barcode\\"`

If I remove the comma from the translation, like this:
`__('Subsequently click on \'scan a barcode\' after which the camera will activate, and point the camera at the QR code.')`

Then the translation is correct:
`"Subsequently click on \\'scan a barcode\\' after which the camera will activate, and point the camera at the QR code.": "Subsequently click on \\'scan a barcode\\' after which the camera will activate, and point the camera at the QR code."`

**Comment by danijelk** [comment]
Would it be an issue just to do it with double quotes instead?

`__("Subsequently click on 's...`

**Comment by RonJeremyR6** [comment]
Wouldn't be an issue if that would have worked. But same result:

`__("Subsequently click on 'scan a barcode', after which the camera will activate, and point the camera at the QR code.")`

Result:
`"Subsequently click on 'scan a barcode": "Subsequently click on 'scan a barcode"`

**Comment by eldor** [comment]
Hi @RonJeremyR6 
Problem is the scanner looks for starting " or ' and ending " or ', therefore it stops at first '
One solution is you change it to a html char like &#39; and then when output use:
`html_entity_decode(__("Subsequently click on &#39;scan a barcode&#39;, after which the camera will activate, and point the camera at the QR code."))`
Or in the translation in Poeditor change the &#39; to correct '

Would that work for you?
