### ISSUE TITLE
translation:upload command overwrites translations with --scan option

### ISSUE THREAD

**Issue by DelDaGhost** [vemcogroup/laravel-translation#19]
Hello,

First of all thx for your awesome-package.
Sadly I've encountered a bug recently:

When running:
`php artisan translation:upload --scan`

All my english-translations are replaced by the translation-keys.

Before it always just scanned the repo for new translation-keys and added them to poeditor without changing the translations.

Laravel-version: 10
package-version: 3.0.8

Best Regards,
Del

**Comment by danijelk** [comment]
Hi Del, are the files changes locally when you run the command?

Do you change the english translations in poeditor?

**Comment by DelDaGhost** [comment]
The English-Translation-file is changed locally:
 -All the translations are replaced with the translation-key (`"key": "value"` is changed to `"key":"key"`)
The new translation-key is not added locally, but added in poeditor.

The German-Translation-file is not changed.

These effects all happen with runnning the command `php artisan translation:upload --scan`.
No changes were made in poeditor from myself.

**Comment by DelDaGhost** [comment]
It looks like the `--scan` - option as well as the `php artisan translation:scan` - command just creates a new english translation-file with all keys in the repository instead of just adding the new translation-keys to the file and therefore overwrites all existing english-translations.

**Comment by danijelk** [comment]
The project is ment to have keys = translation for english, so one can skip remembering keys for translations.
Eg. 'hello world' instead of a key hello_world => 'hello world'

Sounds like you are doing key => translation for english which I can't guess the output of at this time.
