### ISSUE TITLE
vue-i18n translation function $t() not scanning

### ISSUE THREAD

**Issue by cliambrown** [vemcogroup/laravel-translation#2]
I added translation functions from [kazupon/vue-i18n](https://github.com/kazupon/vue-i18n) to my `config/translation.php` as follows:

    'functions' => ['__','$t','this.$t'],

However, the scan didn't catch any translation strings from my Vue components. From a bit of testing, it seems to be an issue with the $ symbol. Is there any way I could make this work?

Thanks!

**Comment by eldor** [comment]
I will look into it and get back to you as soon as possible

**Comment by cliambrown** [comment]
I figured it out! It was a regex issue. In the scanner, the function names get placed directly into a regex pattern without being escaped, so I had to escape it manually:

    'functions' => ['__', '\$t', 'this\.\$t'],

I had tried that previously, but I'd used double quotes instead of single, which meant that the slashes were escaping the characters _before_ they were put into the regex.

**Comment by eldor** [comment]
Hi, thx for the information i'll update the readme and conf description to clarify this.
