### ISSUE TITLE
It will be very helpfull if user can manually add extra files(or directories) to scan.

### ISSUE THREAD

**Issue by nopedev** [vemcogroup/laravel-translation#3]
Thank you for cool package.
I applied this package to my project and the result is very good.

Except one thing that package scans only `*.php` and `*.vue`.

How about the functionality which allows user can manually add files or directories to scan?
something like...
```php
# config/translation.php
...
'extra_files' => [
    resource_path('js/something.js'),
    resource_path('scripts/*.js'),
],
...
```

I thought that it would be very convenient if this kind of functionality is available.

Thank You.

**Comment by eldor** [comment]
Thanks for your suggestion.
Will it solve your issue if we extended the config to have extensions selection?
```php
# config/translation.php
...
 'extensions' => ['*.php', '*.vue'],
...
```

That way you are able to get the scanner du handle .js files as well.

**Comment by nopedev** [comment]
If I have multiple `js` files in single folder, can I scan only `handle.js`?
```
/resources
    /js
        /handle.js
        /somthing.js
        /else.js
        /foobar.js
```

**Comment by eldor** [comment]
It could properly be made, but why would you exclude files from scanning?

**Comment by eldor** [comment]
Added release 1.0.6 where you can select which extensions the scanner scans for.
