### ISSUE TITLE
Translations with an quotes

### ISSUE THREAD

**Issue by Swiek** [vemcogroup/laravel-translation#5]
Hi,

Very nice packages. Makes translating the site a alot easier.
I have an issue with a test like:

> If you don't no what

As a key it's added with \\ in front of the quote. This results in a json key that isn't found in the website and doens't get translated.

Kind regards,

Erwin

**Comment by eldor** [comment]
Hi Erwin,

Thanks for the nice words. 👍

I have tried to add your text in an blade:

```php
{{ __("If you don't no what") }}
```

 and scanned the site and the key is correct as wanted in en.json

```php
"If you don't no what": "If you don't no what",
```

Could you sent some code example and description of your setup?
