### ISSUE TITLE
Q: trim() expects parameter 1 to be string, array given - Key/Value trim error?

### ISSUE THREAD

**Issue by nea** [vemcogroup/laravel-translation#6]
Hi there

Thanks for this convenient package.

I added the compsoer package, configured everything and wanted to download our POEditor translations. It kicks off after `php artisan translation:download` with `Preparing to download languages` and all looks good but then it fails with `trim() expects parameter 1 to be string, array given`. 

I checked where and it is in the `Translation.php` line 123. 
I dumped what is tried to be trimed here, and the input entry is for example

```
array:1 [
  "teams.tab_button.my" => "My Teams"
]
```

Isn't that correct? Key and Value as we prepared. 

Any hint on what the problem might be would be awesome.

Thanks a lot in advance

**Comment by eldor** [comment]
Hi @nea 

Just tested from our on POEditor, and all went smooth.
Could you show me how your terms and translations are setup in POEditor?

It looks like it gets a array from your POEditor instead of a string.

**Comment by nea** [comment]
Hi @eldor 

Thanks for the quick response.

Here is a screenshot.
![image](https://user-images.githubusercontent.com/392035/81907276-cb4be280-95c7-11ea-8ce1-06547b849a5f.png)

Its a term and translation. I do not really know even how to create them differently. Anywhere?


Thanks a lot :)

**Comment by eldor** [comment]
Hi @nea 

I'll try replicate your setup and give you a feedback

**Comment by eldor** [comment]
Hi @nea 

I have made an update that allows for context in POEditor.
Could you try the dev version before i tag it?

**Comment by nea** [comment]
Awesome @eldor 
Worked! I just updated to dev-master and downloaded, works. Translations have been pulled and files look correct.


Thanks a lot for the quick help!!! ^^

**Comment by eldor** [comment]
Ok, ill just run the lasts tests in house and on our own projects and the tag a version 2.0.2
